version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.x
  docker-executor:
    docker:
      - image: docker:20.10

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Build and Push Docker Image
          command: |
            docker login --username thamyis100 --password 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 ghcr.io
            docker build -t ghcr.io/thamyis100/karsajobs/karsajobs-app:v1 .
            docker push ghcr.io/thamyis100/karsajobs-app:v1

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
